### ISSUE TITLE
"ValueError: cannot reshape array" when visualizing Hex SOM projection (with a temporary fix)

### ISSUE THREAD

**Issue by yantingMu** [JulianBesems/UD_IntroProject_2022#2]
## Issue
When running the Code block for visualizing,
```
matplotlib.rcParams.update({'font.size': 10})
plot_hex_map(empirical_codebook.reshape(som.codebook.mapsize + [empirical_codebook.shape[-1]]), 
             titles=df.columns[:-1], shape=[20, 5], colormap=None)
plt.show()
```
sometimes we might see the error:

```
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_31540/2830808868.py in <module>
      1 matplotlib.rcParams.update({'font.size': 10})
----> 2 plot_hex_map(empirical_codebook.reshape(som.codebook.mapsize + [empirical_codebook.shape[-1]]), 
      3              titles=df.columns[:-1], shape=[20, 5], colormap=None)
      4 plt.show()

ValueError: cannot reshape array of size 1170 into shape (20,20,3)
```

This error is highly likely to be due to some of the model's BMUs failing to cluster any data entry, an easy example would be the unit shown in the green circle, where no color point would be considered closest to it.
<img src="https://user-images.githubusercontent.com/79830531/195976206-4f0b1eca-bfc7-482d-ab40-dceb66e7bd8a.png" width="300" height="300">

## Solution

In Code block:
```
empirical_codebook = df.groupby("bmus").mean().values
```
The empirical_codebook will not get a row corresponding to this specific BMU.
This could be easily fixed by:
```
empirical_codebookdf = df.groupby("bmus", as_index=True, dropna=True).mean()
for i in range(map_size_total):
    if i not in empirical_codebookdf.index:
        empirical_codebookdf.loc[i] = [np.NaN for _ in range(len(related_var))]
empirical_codebookdf = empirical_codebookdf.sort_index()
empirical_codebook = empirical_codebookdf.values
```
With these changes, we will get such a plot from visualization:

![Code_gE2CXtJWjv](https://user-images.githubusercontent.com/79830531/195978141-5c26dbf0-1f57-4780-bc72-94202e9f4209.png)

This is due to the function `plot_hex_map()` can not map the right color according to the values given, when `np.NaN` exists. So I have coded a better version`plot_hex_map_with_nan()`  to get the job done. 

(Due to the size of the code, I will upload it as a file: [SOM_Hex_Template.zip](https://github.com/JulianBesems/UD_IntroProject_2022/files/9791635/HexTemplate.zip))

And here is the result, where a gray hex indicates a BMU failed to catch any data:

![Code_0P9ldYXlwI](https://user-images.githubusercontent.com/79830531/195978049-b486393d-49d2-421b-83e8-6b8ed7a7ffd0.png)

Due to time constrictions, I have only implemented(or say, fixed) the plotting for `lattice="hexa"`. 

I would also raise an issue in [sompy](https://github.com/sevamoo/SOMPY) later, and see what's their opinion about it.

**Comment by JulianBesems** [comment]
Thank you very much!! This was very helpful. I'll add this to the notebook asap. It was brought up by students in the seminar today.
